name: Serverless Package & Upload 📦🪣
on: push

jobs:
  build-auther:
    name: Package Auther Zip 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          stable: 'true'
          go-version: '1.23'

      - name: Build
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0  go build -tags lambda.norpc -o bootstrap cmd/lambda/main.go

      - name: Add project code
        run: |
          zip -r ./auther.zip bootstrap


      - uses: actions/upload-artifact@v3
        with:
          name: auther-package
          path: ./auther.zip


  upload-auther:
    name: Upload Auther to S3 🪣
    runs-on: ubuntu-latest
    needs: build-auther
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: auther-package

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy Modified Files
        run: |
          ls
          # Constants
          S3_BUCKET=auther-dev
          S3_KEY=auther.zip
          aws s3 cp auther.zip s3://$S3_BUCKET/$S3_KEY
          
          # Update Lambda function code
          LAMBDA_FUNCTION_NAME=auther-dev-lambda-function
          aws lambda wait function-updated --function-name $LAMBDA_FUNCTION_NAME
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY
          aws lambda wait function-updated --function-name $LAMBDA_FUNCTION_NAME

